// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ResumenTestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void resumenTest() {
    driver.get("http://localhost:8080/RESUMEN-SERVICE/");
    driver.manage().window().setSize(new Dimension(1440, 900));
    driver.findElement(By.xpath("(//div[@id=\'index\']/div/a/img)[3]")).click();
    driver.findElement(By.cssSelector(".show:nth-child(11)")).click();
    driver.findElement(By.linkText("Inicio")).click();
    driver.findElement(By.cssSelector(".ilupa")).click();
    driver.findElement(By.cssSelector(".ilupa")).click();
    driver.findElement(By.cssSelector(".topnav")).click();
    driver.findElement(By.cssSelector(".topnav")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".topnav"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector(".ilupa")).click();
    driver.findElement(By.cssSelector(".ilupa")).sendKeys("ddsdc");
    driver.findElement(By.cssSelector(".ilupa")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector(".ilupa")).click();
    driver.findElement(By.cssSelector(".ilupa")).sendKeys("sdcds");
    driver.findElement(By.cssSelector(".ilupa")).sendKeys(Keys.ENTER);
    driver.findElement(By.linkText("Biblioteca")).click();
    driver.findElement(By.linkText("Tarifas")).click();
    driver.findElement(By.linkText("Biblioteca")).click();
    driver.findElement(By.xpath("(//div[@id=\'index\']/div/a/img)[2]")).click();
    driver.findElement(By.cssSelector(".show:nth-child(10)")).click();
    driver.findElement(By.linkText("Inicio")).click();
  }
}
